[09-hsinchu] Create sprint page
sciwork/swportal pull request #126
Opened 2022-09-10 15:35 UTC by YenPeiChen07

2022-09-10 22:11 UTC, yungyuc requested changes
Everything looks good except the Google Map link.

2022-09-10 22:11 UTC, yungyuc commented on content/pages/sprint/2022/09-hsinchu.rst
> +`清華大學 綜合三館A區 5樓 <https://goo.gl/maps/HPmvSiVwvSjUkQ7dA>`__. Please see the `sprint
The Google Map link leads to "General Physics Laboratory, NTHU 清華大學普物實驗室", which reads a little bit misleading.  How about using just the building's name, not a specific unit in it?

2022-09-11 09:28 UTC, YenPeiChen07 commented on content/pages/sprint/2022/09-hsinchu.rst
> +`清華大學 綜合三館A區 5樓 <https://goo.gl/maps/HPmvSiVwvSjUkQ7dA>`__. Please see the `sprint
Yes, it seems a little bit misleading. I will modify it by using the building's name.

2022-09-12 02:07 UTC, YenPeiChen07 commented
@yungyuc I have updated the Google Map link of the venue. Also changed the building's name so that it fit with the Google Map link.

2022-09-12 02:42 UTC, yungyuc commented
LGTM.  Thanks a lot!

2022-09-12 02:43 UTC, merged