Add after-event contents for scisprint February 2023
sciwork/swportal pull request #169
Opened 2023-02-23 03:05 UTC by YenPeiChen07

Hi, @yungyuc and @cstnaya 

This PR is for addressed #165 by embedding the [Flickr album](https://www.flickr.com/photos/sciwork/albums/72177720305939446) and adding a link for the [blog](https://medium.com/sciwork/scisprint-2023-february-in-taipei-e565f2d19b1a)

I added a raw html to embedding the Flickr album. The reference doc is in [Share or embed Flickr photos/albums](https://www.flickrhelp.com/hc/en-us/articles/4404078014356-Share-or-embed-Flickr-photos-albums). 

I would like to use the group photo in front of AWS as album cover, which looks better. But it seems that it could not customize the album cover, which shows up the first photo in the album.

2023-02-23 11:49 UTC, yungyuc requested changes
It will be great to write a line or two to express our gratitude to the attendees and the sponsor.

I think we might not need a section for the blog if it is moved to the beginning of the page.  And the thank-you message may be in the same passage as the blog link.

2023-02-23 11:49 UTC, yungyuc commented on content/pages/sprint/2023/02-taipei.rst
> +Event Album
These are the highlights of the event.  I think it will be great for them to be shown in the beginning of the page.

2023-02-23 11:49 UTC, yungyuc commented on content/pages/sprint/2023/02-taipei.rst
> +Blog
Maybe the blog entry can go before the album.

2023-03-01 12:19 UTC, YenPeiChen07 commented
@yungyuc I  moved the highlights to the top of the page and added a thank-you message. Please have a check.

2023-03-02 08:07 UTC, yungyuc commented
Please merge as you see fit

2023-03-02 08:47 UTC, merged