Add hackmd note to march meetup page
sciwork/swportal pull request #183
Opened 2023-03-15 11:06 UTC by tychuang1211

2023-03-16 00:17 UTC, yungyuc requested changes
Something seems wrong with netlify.  Please also try to see if it's a real issue.  cc @chestercheng for his awareness.

2023-03-16 00:17 UTC, yungyuc commented on content/pages/meetup/2023/03-nycu.rst
> +Meetup note
Could you add a link targeting this somewhere former in the document?

2023-03-16 01:07 UTC, chestercheng commented
> Something seems wrong with netlify. Please also try to see if it's a real issue. cc @chestercheng for his awareness.

This is the network issue of Netlify, I have manually retry this build.
preview url: https://641267fcf5fcd502bd52662d--swportal.netlify.app

2023-03-20 23:22 UTC, yungyuc commented
@tychuang1211 when there's time could you please make an update to the PR or let us know if there's any issues?

2023-03-21 12:00 UTC, merged

2023-03-21 12:00 UTC, yungyuc commented
Thanks @tychuang1211