add sprint page for scisprint 2023 April
sciwork/swportal pull request #185
Opened 2023-03-17 11:27 UTC by terrychan999

2023-03-17 12:16 UTC, yungyuc commented
For #178

2023-03-17 12:19 UTC, yungyuc requested changes
We should publish the sciwork web page as soon as possible for promotion.  The kktix reg page can be made later.

2023-03-17 12:19 UTC, yungyuc commented on content/pages/sprint/2023/04-hsinchu.rst
> +`Please register at kktix <#>`__ .
Before the kktix page is made, this should be written "TBD" without a link.

2023-03-17 12:19 UTC, yungyuc commented on content/pages/sprint/2023/04-hsinchu.rst
> +To join the sprint, please bring your laptop and `sign up at kktix <#>`__.  You are also very welcome to bring your project, which
Before the kktix page is made, `sign up at kktix` should not be written.  It can be `sign up (TBD)`.

2023-03-17 12:22 UTC, yungyuc commented on content/pages/sprint/2023/04-hsinchu.rst
> +`前沿理論及計算研究中心 (國立清華大學第三綜合大樓 A 區 5 樓) <https://goo.gl/maps/EH2wWtkLQ8qLWd669>`__. Please see the `sprint
Please also add the English name of the venue.

2023-03-17 14:14 UTC, terrychan999 commented
Ok, I got it.

2023-03-18 00:49 UTC, yungyuc approved these changes
LGTM

2023-03-18 00:49 UTC, merged