Add april nycu meetup page
sciwork/swportal pull request #194
Opened 2023-04-07 06:22 UTC by tychuang1211

2023-04-07 23:27 UTC, yungyuc requested changes
There should be a link from the meetup index page to the April page.

2023-04-13 04:42 UTC, tychuang1211 commented
> There should be a link from the meetup index page to the April page.

Oops I forgot that.

2023-04-14 00:42 UTC, yungyuc commented
@tychuang1211 Could you also make the May page?

2023-04-20 05:37 UTC, tychuang1211 commented
> @tychuang1211 Could you also make the May page?

Sure.

2023-04-20 12:40 UTC, yungyuc commented on content/pages/meetup/index.rst
> +  <{filename}2023/03-nycu.rst>`__
Could you please use descending order like the sprint listing page: https://sciwork.dev/sprint/ ?

2023-04-26 22:21 UTC, yungyuc commented
@tychuang1211 Do you have time to take a look at it?

2023-04-27 13:18 UTC, YenPeiChen07 requested changes
Create a meetup note for May and update it in page.

2023-04-29 12:45 UTC, yungyuc approved these changes
LGTM.  Thanks.

2023-04-29 12:45 UTC, merged