feat: add pages for scisprint Taipei
sciwork/swportal pull request #339
Opened 2024-01-23 13:57 UTC by rockleona

2024-01-23 15:08 UTC, kuomc commented
I remember that we cancel the March 23rd scisprint in Hsinchu.

2024-01-23 15:09 UTC, rockleona commented
> I remember that we cancel the March 23rd scisprint in Hsinchu.

So I can just remove it directly?

2024-01-23 15:10 UTC, kuomc requested changes

2024-01-23 15:10 UTC, kuomc commented on content/pages/sprint/index.rst
>  * `(Tentative) Scisprint 2024 March in Hsinchu
I remember that we cancel the March 23rd scisprint in Hsinchu. Please help us remove this page.

2024-01-23 16:13 UTC, rockleona commented
> BTW, I found a blank space between the map and contact us section. Have you encounter this situation? ![image](https://private-user-images.githubusercontent.com/98087916/298997887-ce6288ac-841c-45c6-a03a-1a12faf4283a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjY2NjAsIm5iZiI6MTcwNjAyNjM2MCwicGF0aCI6Ii85ODA4NzkxNi8yOTg5OTc4ODctY2U2Mjg4YWMtODQxYy00NWM2LWEwM2EtMWExMmZhZjQyODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE2MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTNkMDdjOTBmOGZhN2ZiODg1MTk3M2ZiNzdmZmNhOWEwMmY3YjY2MDZhNjQ3ZTJlYWQxZWU0ODZiYTQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o6VWX_8_CWDmWEmU4UIT-eCszHeunPD9gCLBTRVjnA0)

I didn't write the style properly, it's fix now, thanks for pointing out!

2024-01-24 10:38 UTC, kuomc approved these changes

2024-01-24 10:40 UTC, merged