style: update the 202403 seminar appearance
sciwork/swportal pull request #349
Opened 2024-02-04 12:49 UTC by chestercheng

2024-02-04 14:04 UTC, j8xixo12 commented
Hi @chestercheng, could you please help me add the description for the first talk ?

Here is the description:

> Visualization and performance are crucial in scientific computing. However, GUI development requires highly flexible code, while performance-oriented code needs specific tuning that may sacrifice flexibility. In this talk, we will demonstrate how to use a hybrid architecture that balances performance and flexibility in developing visualization applications.

2024-02-04 18:03 UTC, kuomc requested changes
I will add the remaining event information after it is released.

2024-02-05 11:32 UTC, chestercheng commented
@kuomc I have removed 'Tentative' from the title and added a description for the technical talks.
Please take a look.

2024-02-05 21:09 UTC, kuomc approved these changes

2024-02-05 21:10 UTC, merged