feat(seminar): add draft page of seminar summer 2024
sciwork/swportal pull request #398
Opened 2024-05-09 14:13 UTC by rockleona

2024-05-13 12:48 UTC, yungyuc requested changes
- [x] Make confirmed topics explicit.
- [x] Update topics.
- [ ] For talks without confirmed topics, list only speaker names.
- [ ] Remove unconfirmed talks.

Please make this PR ready for review since you are requesting review.  Make a global comment when you update the contents and ready for the follow-up review.

2024-05-13 12:48 UTC, yungyuc commented on content/pages/conference/2024/06-seminar.rst
> +* Visualization that balances performance and flexibility for scientific computing by **Chun-Hsu Lai**
Confirmed topics should be made explicit and separate from unconfirmed ones.  Check the workbook.

2024-05-13 12:48 UTC, yungyuc commented on content/pages/conference/2024/06-seminar.rst
> +* Cytnx Development Update by **高英哲** and **陳柏中**
The topic of Cytnx is confirmed.  Please take a look at the workbook.

2024-05-13 12:48 UTC, yungyuc commented on content/pages/conference/2024/06-seminar.rst
> +* Python Documentation Translation by **Matt Wang** and **Li-Hung Wang**
Please list only speaker names for the talk whose topics are not confirmed.

2024-05-13 14:05 UTC, rockleona commented
> * [ ]  Make confirmed topics explicit.
> * [ ]  Update topics.
> * [ ]  For talks without confirmed topics, list only speaker names.
> * [ ]  Remove unconfirmed talks.
> 
> Please make this PR ready for review since you are requesting review. Make a global comment when you update the contents and ready for the follow-up review.

I've confirmed that these items are already updated, please review.

2024-05-14 05:37 UTC, yungyuc commented
LGTM.  Merge.

2024-05-14 05:37 UTC, merged