Update 20240828 meetup information
sciwork/swportal pull request #456
Opened 2024-08-26 07:15 UTC by ThreeMonth03

According to the issue #455 ,this PR adds a new webpage and showcases the schedule for the 8/28 Meetup at NYCU.

2024-08-26 07:21 UTC, yungyuc commented
@kuomc @YenPeiChen07 please help review.

@ThreeMonth03 please update the meetup listing page too.

2024-08-26 07:24 UTC, ThreeMonth03 commented
> @kuomc @YenPeiChen07 please help review.
> 
> @ThreeMonth03 please update the meetup listing page too.

@yungyuc Thanks for your notification. I fix it.

2024-08-26 09:47 UTC, YenPeiChen07 requested changes
@ThreeMonth03 Thank you for adding the meetup information. It looks good overall, but there is a small part need to be updated.

2024-08-26 10:41 UTC, ThreeMonth03 commented on content/pages/meetup/2024/0828-nycu.rst
> +Meetup 2024 August 21st in NYCU
> The title needs to be updated with the correct date.

Fixed.

2024-08-26 10:42 UTC, ThreeMonth03 commented on content/pages/meetup/2024/0828-nycu.rst
> +Meetup 2024 August 21st in NYCU
Thanks for your suggestion. @YenPeiChen07 You could review this pr when you are available.

2024-08-26 13:48 UTC, kuomc commented
Hi @ThreeMonth03 , thank you for updating the meetup information and the new meetup page look good, but I found an issue about the GitHub master branch. You use the force push to commit the master branch. I used to merge the commit into the develop branch first to check the new features or pages work well on netlify, and open an new PR to merge commit into master branch from develop branch to publish the new pages. Without special permissions, other people shouldn't be able to directly push or merge the master branch.

Hi @yungyuc @YenPeiChen07 , I didn't see this situation before and I'm not sure if it's good idea to merge the commit into master directly. Please comment if you have some idea.

2024-08-26 14:35 UTC, YenPeiChen07 commented
> Hi @ThreeMonth03 , thank you for updating the meetup information and the new meetup page look good, but I found an issue about the GitHub master branch. You use the force push to commit the master branch. I used to merge the commit into the develop branch first to check the new features or pages work well on netlify, and open an new PR to merge commit into master branch from develop branch to publish the new pages. Without special permissions, other people shouldn't be able to directly push or merge the master branch.
> 
> Hi @yungyuc @YenPeiChen07 , I didn't see this situation before and I'm not sure if it's good idea to merge the commit into master directly. Please comment if you have some idea.

Thanks, @kuomc, for bringing to our attention.

To protect `master` branch and follow follow [the rule of contribution](https://github.com/sciwork/swportal/blob/e6a8cfd470090eb7582d9d30c1774fa2db905fd7/README.rst#L21), I recommend either create a PR against the `develop` branch or [changing the branch base of this PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).

From my view, filing another PR against against `develop` branch for tracking and merging would be safer. We can then close this one without directly merging into `master`.

@ThreeMonth03 Could you please help with filing another PR against the `develop` branch?

2024-08-26 14:44 UTC, yungyuc commented
@kuomc @YenPeiChen07 with the repository writing permission you may change the destination branch.  I just changed it from `master` to `develop`.

And thanks to @kuomc for highlighting the issue.  @ThreeMonth03 please be careful next time and review the [README](https://github.com/sciwork/swportal/blob/develop/README.rst).

2024-08-26 14:49 UTC, ThreeMonth03 commented
> @kuomc @YenPeiChen07 with the repository writing permission you may change the destination branch. I just changed it from `master` to `develop`.
> 
> And thanks to @kuomc for highlighting the issue. @ThreeMonth03 please be careful next time and review the [README](https://github.com/sciwork/swportal/blob/develop/README.rst).

My blunder. Thanks for @kuomc explanation, I will notice to make a pull request to the right branch.

2024-08-27 02:02 UTC, yungyuc commented
@kuomc @YenPeiChen07 Could you please review again?  We should publish the web page as soon as possible.

2024-08-27 03:45 UTC, YenPeiChen07 commented
LGTM.

2024-08-27 03:45 UTC, merged